/*
 * Piccoli eroi in pixel art, disegnati a caratteri: ogni lettera è un colore
 * della palette, il punto è trasparente. Sono omaggi "alla lontana" ai
 * personaggi delle varie scuole di fumetto, non riproduzioni ufficiali.
 */
export const PALETTE: Record<string, string> = {
  k: '#0f0d0d',
  w: '#fdfaf3',
  r: '#e2222a',
  d: '#a3141a',
  b: '#2b3fd9',
  c: '#0074e8',
  y: '#ffcf3f',
  s: '#f5c79b',
  t: '#d99a6c',
  o: '#e8740c',
  n: '#7a4420',
  j: '#3a5a9a',
  g: '#b9b9c4',
  x: '#3a3a46',
  p: '#ea8cc3',
  a: '#8ec5f0',
  e: '#d8246f',
}

export const SPRITES = {
  ragno: [
    '......kkkk......',
    '....kkrrrrkk....',
    '...krrrrrrrrk...',
    '...krrdrrdrrk...',
    '..krkkkrrkkkrk..',
    '..kkwwwkkwwwkk..',
    '..krkwwrrwwkrk..',
    '...krkkrrkkrk...',
    '....kkrrrrkk....',
    '...kbbrrrrbbk...',
    '..kbbrrkkrrbbk..',
    '.kbbbrrkkrrbbbk.',
    '.krkbrrrrrrbkrk.',
    '.krkbrrrrrrbkrk.',
    '.kdkkbbbbbbkkdk.',
    '...kbbbbbbbbk...',
    '...kbbbkkbbbk...',
    '...kbbbkkbbbk...',
    '...krrrkkrrrk...',
    '...kkkkkkkkkk...',
  ],
  batman: [
    '....k......k....',
    '....kk....kk....',
    '....kkkkkkkk....',
    '...kkkkkkkkkk...',
    '...kkwwkkwwkk...',
    '...kkkkkkkkkk...',
    '...kksssssskk...',
    '....kskkkksk....',
    '.kkggggggggggkk.',
    'kkgggkkkkkkgggkk',
    'kkggggkkkkggggkk',
    'kkgkgggkkgggkgkk',
    'kkgkggggggggkgkk',
    'kkkkyyyyyyyykkkk',
    'kk.kggggggggk.kk',
    'kk.kgggkkgggk.kk',
    'kk.kgggkkgggk.kk',
    'k..kgggkkgggk..k',
    'k..kkkkkkkkkk..k',
    '...kkkkkkkkkk...',
  ],
  crazyDiamond: [
    '.....kkkkkk.....',
    '....kaaaaaak....',
    '...kaaaaaaaak...',
    '...kappppppak...',
    '...kakkppkkak...',
    '...kappppppak...',
    '...kappkkppak...',
    '....kkppppkk....',
    '..kaakppppkaak..',
    '.kaeakppppkaeak.',
    '.kaakppeeppkaak.',
    '.kpkppppppppkpk.',
    '.kpkppppppppkpk.',
    '.kakkaeaaeakkak.',
    '...kppppppppk...',
    '...kpppkkpppk...',
    '...kaeakkaeak...',
    '...kpppkkpppk...',
    '...kpppkkpppk...',
    '...kaaakkaaak...',
  ],
  vegeta: [
    '.......kk.......',
    '.....k.kk.k.....',
    '.....kkkkkk.....',
    '....kkkkkkkk....',
    '....kkkkkkkk....',
    '....ksskkssk....',
    '....kksssskk....',
    '....kskssksk....',
    '....kssttssk....',
    '.....kssssk.....',
    '..kywwwbbwwwyk..',
    '.kbkwwwwwwwwkbk.',
    '.kbkwyywwyywkbk.',
    '.kbkwwwwwwwwkbk.',
    '.kwkbbbbbbbbkwk.',
    '...kbbbbbbbbk...',
    '...kbbbkkbbbk...',
    '...kbbbkkbbbk...',
    '...kwwwkkwwwk...',
    '...kyyykkyyyk...',
  ],
  gatsu: [
    '.kk......k.k.k....',
    'kggk....kkkkkkk...',
    'kggk...kkkkkkkkk..',
    'kggk....kksskssk..',
    'kggk....kskssksk..',
    'kggk....ksttttsk..',
    'kggk.....kssssk...',
    'kggk....kxkkkkxk..',
    'kggk..kkxxxxxxxxkk',
    'kggk.kxxxxxxxxxxxk',
    'kkkkkxxxxxxxxxxxxk',
    '.nn.kxkxxxxxxxxkxk',
    '.nnksskxxxxxxxxkgk',
    '.nn.kknnnnnnnnnkkk',
    '.kk....kxxxxxxkkkk',
    '.......kxxkkxxkkkk',
    '.......kxxkkxxkkkk',
    '.......kxxkkxxkkk.',
    '......kxxxkkxxxkk.',
    '......kkkkkkkkkk..',
  ],
  indagatore: [
    '.....kkkkkk.....',
    '....kkkkkkkk....',
    '...kkkkkkkkkk...',
    '...kkkssssskk...',
    '...kkskssksk....',
    '...kkssssssk....',
    '....kssttsk.....',
    '....kkksskkk....',
    '...kxxrrrrxxk...',
    '..kxxxrrrrxxxk..',
    '.kxxxxrrrrxxxxk.',
    '.kxkxxrrrrxxkxk.',
    '.kxkxxrrrrxxkxk.',
    '.kskxxxxxxxxksk.',
    '....kjjjjjjk....',
    '....kjjkkjjk....',
    '....kjjkkjjk....',
    '....kjjkkjjk....',
    '...knnnkknnnk...',
    '...kkkkkkkkkk...',
  ],
  paperino: [
    '.....kkkkkk.....',
    '....kbbbbbbk....',
    '...kkkkkkkkkk...',
    '...kwwwwwwwwk...',
    '...kwwkwwkwwk...',
    '...kwwwwwwwwk...',
    '..kookooooooko..',
    '...koooooooook..',
    '....kwwwwwwk....',
    '...kbbrrrrbbk...',
    '..kbbbbrrbbbbk..',
    '.kwkbbbbbbbbkwk.',
    '.kwkbbbbbbbbkwk.',
    '.kwkkwwwwwwkkwk.',
    '...kwwwwwwwwk...',
    '....kwwwwwwk....',
    '.....oo..oo.....',
    '.....oo..oo.....',
    '..ooooo..ooooo..',
  ],
  paperone: [
    '.....kkkkkk.....',
    '.....kkkkkk.....',
    '.....kkkkkk.....',
    '.....kddddk.....',
    '...kkkkkkkkkk...',
    '...kwwwwwwwwk...',
    '...kwwkwwkwwk...',
    '...kwwwwwwwwk...',
    '..kookooooooko..',
    '...koooooooook..',
    '...krrkwwkrrk...',
    '..krrrrkkrrrrk..',
    '.krkrrrrrrrrkrk.',
    '.kwkrryrryrrkwn.',
    '...krrrrrrrrk.n.',
    '...kwwwwwwwwk.n.',
    '....kwwwwwwk..n.',
    '.....ko..ok...n.',
    '....kwwk.kwwk.n.',
    '..ooooo..ooooo.n',
  ],
  robot: [
    '.......kk.......',
    '.......yy.......',
    '....kkkkkkkk....',
    '...kggggggggk...',
    '...kgkwggkwgk...',
    '...kgkkggkkgk...',
    '...kggggggggk...',
    '...kgkkkkkkgk...',
    '....kkkkkkkk....',
    '..kkggggggggkk..',
    '.kgkgrrggyygkgk.',
    '.kgkggggggggkgk.',
    '.kkkggggggggkkk.',
    '...kgggkkgggk...',
    '...kgggkkgggk...',
    '..kkkkkkkkkkkk..',
  ],
}

export type SpriteName = keyof typeof SPRITES
